### PR TITLE
added tests with IV, weights and fixed effects

### PR DESCRIPTION
**Pull request by duncanhobbs**
I added some additional tests using instrumental variables, weights, and fixed effects. I also added some tests using subsets of the data. 

I can continue to add more tests if there are others that would be useful.

### CODE REVIEW

**Comment by matthieugomez** [comment]
Great! Did you check that the result was consistent with another software, like Stata reghdfe or R lfe?

**Comment by duncanhobbs** [comment]
I checked that the results were consistent with Stata reghdfe. 

I can keep this PR open if you want me to add more tests for things.

**Comment by matthieugomez** [comment]
Ok that's great.  The fact that the tests fail now means that, apparently, in some cases, I obtain different results compared to reghdfe?

**Comment by duncanhobbs** [comment]
The version of reghdfe I am using is an older version (I think 3.2.9). Did you write the other tests using a specific version of the command?

I also attached the reghdfe output from the test that failed.

reghdfe-test-missing-fixed-effects

**Comment by matthieugomez** [comment]
Ok that’s very useful. Can you comment the tests that fail so that (i) tests pass when merging your pull request (ii) i have an idea on how many tests fail? I’ll then try to look for the bug after merging.

**Pull request merged**
